baseURL = "https://edu.chainguard.dev/"
canonifyURLs = false
disableAliases = false
disableHugoGeneratorInject = true
enableEmoji = false
enableGitInfo = false
enableRobotsTXT = true
languageCode = "en-US"
paginate = 7
rssLimit = 10
ignoreErrors = ["image-not-found"]
# googleAnalytics = 'G-05CPR1LJPR' # Handled by GTM now
[params]
  googleTagManager = "GTM-58WV5RN"
# Multilingual
defaultContentLanguage = "en"
disableLanguages = ["de", "nl"]
# defaultContentLanguageInSubdir = true
# add redirects/headers
[outputs]
home = ["HTML", "RSS", "ALIASES", "REDIRECTS", "HEADERS", "TXT", "FULLTXT", "AIMETADATA", "AISITEMAP", "CONCEPTS"]
section = ["HTML", "RSS", "SITEMAP"]
# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
suffixes = [""]
delimiter = ""
# add output format for netlify _redirects
[outputFormats.REDIRECTS]
mediaType = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true
# add output format for alias meta refresh to 301 # redirects
[outputFormats.ALIASES]
mediaType = "text/netlify"
baseName = "_aliases"
isPlainText = true
notAlternative = true
# add output format for netlify _headers
[outputFormats.HEADERS]
mediaType = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true
# add output format for section sitemap.xml
[outputFormats.SITEMAP]
mediaType = "application/xml"
baseName = "sitemap"
isHTML = false
isPlainText = true
noUgly = true
rel  = "sitemap"
# add output format for llms.txt
[outputFormats.TXT]
mediaType = "text/plain"
baseName = "llms"
isPlainText = true
# add output format for llms-full.txt
[outputFormats.FULLTXT]
mediaType = "text/plain"
baseName = "llms-full"
isPlainText = true
# add output format for ai-metadata.json
[outputFormats.AIMETADATA]
mediaType = "application/json"
baseName = "ai-metadata"
isPlainText = true
notAlternative = true
# add output format for ai-sitemap.json
[outputFormats.AISITEMAP]
mediaType = "application/json"
baseName = "ai-sitemap"
isPlainText = true
notAlternative = true
# add output format for concepts.json
[outputFormats.CONCEPTS]
mediaType = "application/json"
baseName = "concepts"
isPlainText = true
notAlternative = true
[caches]
  [caches.getjson]
    dir = ":cacheDir/:project"
    maxAge = "10s"
[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5
[taxonomies]
  contributor = "contributors"
  tags = "tags"
[related]
  # Only include matches with rank >= threshold
  threshold = 60
  # Show up to 5 related articles
  includeNewer = true
  toLower = false
  [[related.indices]]
    name = "section"
    weight = 100  # Higher weight on section since tags need work
  [[related.indices]]
    name = "tags"
    weight = 50   # Lower weight until tags are improved
  [[related.indices]]
    name = "title"
    weight = 30   # Title similarity can help
  [[related.indices]]
    name = "date"
    weight = 10
[permalinks]
  blog = "/blog/:title/"
# docs = "/docs/1.0/:sections[1:]/:title/"
[minify.tdewolff.html]
  keepWhitespace = false
[module]
  [module.hugoVersion]
    extended = true
    min = "0.80.0"
    max = ""
  [[module.mounts]]
    source = "node_modules/@hyas/doks/archetypes"
    target = "archetypes"
  [[module.mounts]]
    source = "node_modules/@hyas/doks/assets"
    target = "assets"
#  [[module.mounts]]
#    source = "node_modules/@hyas/doks/content"
#    target = "content"
  [[module.mounts]]
    source = "node_modules/@hyas/doks/data"
    target = "data"
  [[module.mounts]]
    source = "node_modules/@hyas/doks/layouts"
    target = "layouts"
  [[module.mounts]]
    source = "node_modules/@hyas/doks/static"
    target = "static"
  [[module.mounts]]
    source = "node_modules/flexsearch"
    target = "assets/js/vendor/flexsearch"
  [[module.mounts]]
    source = "node_modules/katex"
    target = "assets/js/vendor/katex"
  [[module.mounts]]
    source = "node_modules/mermaid"
    target = "assets/js/vendor/mermaid"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"
#  [[module.mounts]]
#    source = "content"
#    target = "content"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "archetypes"
    target = "archetypes"
  [[module.mounts]]
    source = "data"
    target = "data"