version: 2
updates:
  - package-ecosystem: gomod
    directory: "./tools/rumble"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      gomod:
        update-types:
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "security-team"
    labels:
      - "dependencies"
      - "github-actions"
      - "security"
    groups:
      actions:
        update-types:
          - "minor"
          - "patch"
          
  # Python dependencies for documentation compilation
  - package-ecosystem: "pip"
    directory: "/scripts"
    schedule:
      interval: "weekly"
    reviewers:
      - "security-team"
    labels:
      - "dependencies"
      - "security"
      - "documentation"
