# Gitleaks configuration for documentation compilation

[allowlist]
description = "Global allow list for documentation"
paths = [
    '''static/downloads/chainguard-complete-docs\.md''',
    '''\.github/workflows/.*\.yml''',
]

[[rules]]
description = "AWS Access Key"
id = "aws-access-key"
regex = '''(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}'''
tags = ["key", "AWS"]

[[rules]]
description = "AWS Secret Key"
id = "aws-secret-key"
regex = '''(?i)aws(.{0,20})?(?-i)['\"][0-9a-zA-Z\/+]{40}['\"]'''
tags = ["key", "AWS"]

[[rules]]
description = "GitHub Personal Access Token"
id = "github-pat"
regex = '''ghp_[0-9a-zA-Z]{36}'''
tags = ["key", "GitHub"]

[[rules]]
description = "GitHub OAuth Access Token"
id = "github-oauth"
regex = '''gho_[0-9a-zA-Z]{36}'''
tags = ["key", "GitHub"]

[[rules]]
description = "SSH Private Key"
id = "ssh-private-key"
regex = '''-----BEGIN( RSA| DSA| EC| OPENSSH)? PRIVATE KEY( BLOCK)?-----'''
tags = ["key", "SSH"]

[[rules]]
description = "Google API Key"
id = "google-api-key"
regex = '''AIza[0-9A-Za-z\-_]{35}'''
tags = ["key", "Google"]

[[rules]]
description = "Slack Token"
id = "slack-token"
regex = '''(xox[pborsa]-[0-9]{12}-[0-9]{12}-[0-9]{12}-[a-z0-9]{32})'''
tags = ["token", "Slack"]

[[rules]]
description = "Generic API Key"
id = "generic-api-key"
regex = '''(?i)(api_key|apikey|api-key)(.{0,20})?['|"][0-9a-zA-Z]{32,45}['|"]'''
tags = ["key", "Generic"]

[[rules]]
description = "Generic Secret"
id = "generic-secret"
regex = '''(?i)(secret|password|passwd|pwd)(.{0,20})?['|"][0-9a-zA-Z]{32,45}['|"]'''
tags = ["secret", "Generic"]

[[rules]]
description = "Private Key"
id = "private-key"
regex = '''(?i)(private_key|privatekey)(.{0,20})?['|"][0-9a-zA-Z]{32,45}['|"]'''
tags = ["key", "Generic"]

# Allow certain patterns in documentation
[[rules.allowlist]]
description = "Allow example keys in documentation"
regex = '''example|sample|demo|test|dummy|placeholder|your-.*-here|<.*>|\$\{.*\}'''

[[rules.allowlist]]
description = "Allow code blocks"
regex = '''```[\s\S]*?```'''

[[rules.allowlist]]
description = "Allow markdown links"
regex = '''\[.*\]\(.*\)'''