package:
  name: academy-policy-controller-install
  version: 0.1.0
  description: Chainguard Academy policy-controller package showing how to install
  target-architecture:
    - x86_64
  copyright:
    - license: Apache-2.0
      paths:
        - "*"

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    packages:
      - alpine-baselayout-data
      - ca-certificates-bundle
      - busybox

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/k3s-io/k3s/releases/download/v1.25.7%2Bk3s1/k3s
      expected-sha256: 75b7d83f598fa96ec672e01c9cc6ab1009450b9519f662e8eb7cf0a0039379b4
      extract: false
  - name: setup steps
    runs: |
      mkdir -p \
        "${{targets.destdir}}/usr/bin" \
        "${{targets.destdir}}/usr/local/bin" \
        "${{targets.destdir}}/etc/profile.d" \
        "${{targets.destdir}}/etc/sudoers.d"
      mv ./k3s "${{targets.destdir}}/usr/local/bin/k3s"
      chmod 755 "${{targets.destdir}}/usr/local/bin/k3s"
      echo "inky ALL=(ALL:ALL) NOPASSWD: ALL" > "${{targets.destdir}}/etc/sudoers.d/inky"
      cp ./profile.sh "${{targets.destdir}}/etc/profile.d/inky-profile.sh"

