#!/usr/bin/env python3
"""
Chainguard AI Documentation MCP Server

A Model Context Protocol server that provides AI assistants with searchable
access to Chainguard documentation including container images, security info,
and tooling guides.

Ported to the mcp 2.0 high-level `MCPServer` API (decision: DOCS-89). All tool
logic and both index classes are unchanged from the 1.x server; only the MCP
glue (registration + transport) was rewritten.
"""

import argparse
import functools
import json
import logging
import os
import re
from typing import Any, Annotated, Dict, List, Literal, Optional

# MCP SDK imports (2.0 high-level API)
try:
    from mcp.server import MCPServer
    from pydantic import Field
except ImportError:
    import sys

    print(
        "Error: MCP SDK 2.x not installed. Install with: pip install 'mcp>=2,<3'",
        file=sys.stderr,
    )
    sys.exit(1)

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("chainguard-ai-docs-mcp")

# Documentation file path
DOCS_PATH = os.getenv("DOCS_PATH", "/docs/chainguard-ai-docs.md")

# Image catalog file path (generated by generate_image_catalog.py)
CATALOG_PATH = os.getenv("CATALOG_PATH", "/docs/image-catalog.json")

# Input length limits to prevent CPU DoS on string operations
MAX_INPUT_LEN = 500
MAX_RESULTS_CAP = 20


def extract_image_names(container_section: str) -> List[str]:
    """Return image names from the compiled '## Container Images' section text.

    compile_docs.py writes each image as
        ### <name>
        <README content>
        <!-- IMAGE_SEPARATOR -->
    so we split on the separator and take the first '### ' heading of each block.
    This is robust to '###' subheadings inside a README (which defeated the older
    regexes) and to image names containing underscores (e.g. sql_exporter).
    Uppercase scaffolding directories such as TEMPLATE are excluded by the
    lowercase-only name pattern.

    NOTE: keep this identical to extract_image_names in
    scripts/generate_image_catalog.py. The MCP server and the catalog must agree
    on the image set; see DOCS-138.
    """
    names = []
    for block in container_section.split("<!-- IMAGE_SEPARATOR -->"):
        heading = re.search(r"^### (\S+)\s*$", block, re.MULTILINE)
        if heading and re.fullmatch(r"[a-z0-9][a-z0-9_-]*", heading.group(1)):
            names.append(heading.group(1))
    return names


class ChaguardDocsIndex:
    """Index of Chainguard documentation sections for efficient retrieval."""

    def __init__(self, docs_content: str):
        self.content = docs_content
        self.sections = self._parse_sections()
        self.images = self._extract_images()

    def _parse_sections(self) -> Dict[str, str]:
        """Parse markdown into logical sections."""
        sections = {}
        current_section = None
        current_content = []

        for line in self.content.split("\n"):
            # Top-level headers indicate new sections
            if line.startswith("# "):
                if current_section:
                    sections[current_section] = "\n".join(current_content)
                current_section = line[2:].strip()
                current_content = [line]
            elif current_content:
                current_content.append(line)

        # Add last section
        if current_section:
            sections[current_section] = "\n".join(current_content)

        # Also parse individual container images as separate sections
        # Find the Container Images section and extract individual image docs
        container_images_match = re.search(
            r"^## Container Images\n", self.content, re.MULTILINE
        )
        if container_images_match:
            start_pos = container_images_match.end()
            section_content = self.content[start_pos:]

            # Use regex to find all image sections (### header followed by content until next separator or end)
            # Pattern: ### image-name followed by content until <!-- IMAGE_SEPARATOR --> or end of string.
            # Name class allows underscores to match images like sql_exporter (DOCS-138).
            image_pattern = (
                r"### ([a-z0-9][a-z0-9_-]*)\n(.*?)(?=\n<!-- IMAGE_SEPARATOR -->|\Z)"
            )
            for match in re.finditer(image_pattern, section_content, re.DOTALL):
                image_name = match.group(1)
                image_content = f"### {image_name}\n{match.group(2).strip()}"
                sections[f"image:{image_name}"] = image_content

        return sections

    def _extract_images(self) -> List[str]:
        """Extract list of container image names from docs."""
        container_images_match = re.search(
            r"^## Container Images\n", self.content, re.MULTILINE
        )
        if container_images_match:
            names = extract_image_names(self.content[container_images_match.end() :])
            if names:
                return sorted(set(names))

        # Fallback: look for cgr.dev references if no images found from headers
        images = set()
        for match in re.finditer(r"cgr\.dev/chainguard/([a-z0-9\-]+)", self.content):
            images.add(match.group(1))
        return sorted(images)

    def search(self, query: str, max_results: int = 5) -> List[Dict[str, str]]:
        """Search documentation for relevant content."""
        query_lower = query.lower()
        results = []

        for section_name, section_content in self.sections.items():
            # Simple relevance scoring based on query term frequency
            content_lower = section_content.lower()
            score = content_lower.count(query_lower)

            if score > 0:
                # Extract a relevant snippet
                lines = section_content.split("\n")
                snippet_lines = []
                for line in lines[:50]:  # First 50 lines of section
                    if query_lower in line.lower():
                        snippet_lines.append(line)
                        if len(snippet_lines) >= 5:
                            break

                results.append(
                    {
                        "section": section_name,
                        "score": score,
                        "snippet": "\n".join(snippet_lines[:5]),
                        "full_content": section_content[:2000],  # First 2000 chars
                    }
                )

        # Sort by relevance and return top results
        results.sort(key=lambda x: x["score"], reverse=True)
        return results[:max_results]

    def get_image_docs(self, image_name: str) -> Optional[str]:
        """Get documentation for a specific container image."""
        # First, try to find the image-specific section (with image: prefix)
        image_key = f"image:{image_name}"
        if image_key in self.sections:
            return self.sections[image_key]

        # Fallback: try without exact match (case-insensitive)
        for section_name, section_content in self.sections.items():
            if (
                section_name.startswith("image:")
                and image_name.lower() in section_name.lower()
            ):
                return section_content

        # Last resort: search for any mention
        results = self.search(image_name, max_results=1)
        if results:
            return results[0]["full_content"]

        return None

    def get_security_content(self) -> str:
        """Get security and CVE related content."""
        security_terms = ["security", "cve", "vulnerability", "sbom", "signature"]
        relevant_sections = []

        for section_name, section_content in self.sections.items():
            if any(term in section_name.lower() for term in security_terms):
                relevant_sections.append(f"# {section_name}\n\n{section_content}")

        if relevant_sections:
            return "\n\n---\n\n".join(relevant_sections)

        return "No specific security documentation found."

    def get_tool_docs(self, tool_name: str) -> Optional[str]:
        """Get documentation for Chainguard tools (wolfi, apko, melange, chainctl)."""
        tool_lower = tool_name.lower()

        for section_name, section_content in self.sections.items():
            if tool_lower in section_name.lower():
                return section_content

        # Fallback to search
        results = self.search(tool_name, max_results=1)
        if results:
            return results[0]["full_content"]

        return None


class ImagesCatalog:
    """Catalog of Chainguard images and package mappings from image-catalog.json."""

    def __init__(self, catalog_path: str):
        self.catalog = self._load_catalog(catalog_path)

    def _load_catalog(self, path: str) -> Dict[str, Any]:
        """Load the catalog JSON, returning empty structure on failure."""
        try:
            with open(path, "r") as f:
                return json.load(f)
        except Exception as e:
            logger.warning(f"Could not load image catalog from {path}: {e}")
            return {
                "metadata": {},
                "images": {},
                "packages": {},
            }

    @property
    def available(self) -> bool:
        """Check if catalog data is loaded."""
        return bool(self.catalog.get("images"))

    def list_images(self, filter_term: Optional[str] = None) -> List[Dict[str, Any]]:
        """List images, optionally filtered by name."""
        results = []
        for name, entry in self.catalog.get("images", {}).items():
            if filter_term and filter_term.lower() not in name.lower():
                continue

            item = {
                "name": name,
                "registry_ref": entry.get("registry_ref", ""),
                "has_documentation": entry.get("has_documentation", False),
            }
            results.append(item)

        return sorted(results, key=lambda x: x["name"])

    def find_package_equivalent(
        self, package: str, distro: Optional[str] = None
    ) -> List[Dict[str, Any]]:
        """Find Wolfi package equivalents for a Debian, Fedora, or Alpine package."""
        results = []
        packages = self.catalog.get("packages", {})

        distros_to_search = [distro] if distro else list(packages.keys())

        for d in distros_to_search:
            pkg_map = packages.get(d, {})
            if package in pkg_map:
                results.append(
                    {
                        "distro": d,
                        "original_package": package,
                        "wolfi_packages": pkg_map[package],
                    }
                )
            else:
                # Case-insensitive search
                for key, value in pkg_map.items():
                    if key.lower() == package.lower():
                        results.append(
                            {
                                "distro": d,
                                "original_package": key,
                                "wolfi_packages": value,
                            }
                        )
                        break

        return results

    @staticmethod
    def _is_valid_image_name(name: str) -> bool:
        """Validate image name to prevent path traversal or injection."""
        return bool(re.fullmatch(r"[a-z0-9][a-z0-9\-]{0,127}", name))

    def check_live_image(self, name: str) -> Dict[str, Any]:
        """Check image freshness via live registry query to cgr.dev."""
        result = {
            "name": name,
            "registry_ref": f"cgr.dev/chainguard/{name}",
            "live_check": False,
            "tags": [],
            "error": None,
        }

        if not self._is_valid_image_name(name):
            result["error"] = "Invalid image name"
            return result

        # Add catalog info if available
        catalog_entry = self.catalog.get("images", {}).get(name)
        if catalog_entry:
            result["has_documentation"] = catalog_entry.get("has_documentation", False)

        try:
            import httpx
        except ImportError:
            result["error"] = "httpx not available; returning catalog data only"
            return result

        try:
            url = f"https://cgr.dev/v2/chainguard/{name}/tags/list"
            with httpx.Client(timeout=10.0) as client:
                resp = client.get(url, headers={"Accept": "application/json"})
                if resp.status_code == 200:
                    data = resp.json()
                    result["live_check"] = True
                    result["tags"] = data.get("tags", [])[:20]
                else:
                    result["error"] = f"Registry returned HTTP {resp.status_code}"
        except Exception as e:
            result["error"] = f"Live check failed: {str(e)}"

        return result


# Initialize MCP server
server = MCPServer("chainguard-ai-docs")

# Load and index documentation
logger.info(f"Loading documentation from {DOCS_PATH}")
try:
    with open(DOCS_PATH, "r") as f:
        docs_content = f.read()
    docs_index = ChaguardDocsIndex(docs_content)
    logger.info(f"Indexed {len(docs_index.sections)} documentation sections")
    logger.info(f"Found {len(docs_index.images)} container images")
except Exception as e:
    logger.error(f"Failed to load documentation: {e}")
    docs_index = None

# Load image catalog
logger.info(f"Loading image catalog from {CATALOG_PATH}")
catalog = ImagesCatalog(CATALOG_PATH)
if catalog.available:
    logger.info(
        f"Catalog loaded: {catalog.catalog['metadata'].get('total_images', 0)} images"
    )
else:
    logger.warning(
        "Image catalog not available; catalog-based tools will return limited results"
    )


def safe_tool(fn):
    """Wrap a tool so uncaught exceptions are logged and never leak to the client.

    Preserves the 1.x server's behavior: on error, log with a stack trace and
    return a sanitized message instead of the raw exception text.
    """

    @functools.wraps(fn)
    def wrapper(*args, **kwargs):
        try:
            return fn(*args, **kwargs)
        except Exception:
            logger.error(f"Error handling tool call {fn.__name__}", exc_info=True)
            return "An internal error occurred. Please try again or adjust your query."

    return wrapper


DOCS_UNAVAILABLE = "Error: Documentation not loaded. Please check server logs."


@server.tool(
    description="Search across all Chainguard documentation for relevant content"
)
@safe_tool
def search_docs(
    query: Annotated[
        str,
        Field(
            description="Search query (e.g., 'python image security', 'CVE management')"
        ),
    ],
    max_results: Annotated[
        int,
        Field(
            description="Maximum number of results to return (default: 5)",
            le=MAX_RESULTS_CAP,
        ),
    ] = 5,
) -> str:
    if docs_index is None:
        return DOCS_UNAVAILABLE

    query = query[:MAX_INPUT_LEN]
    max_results = min(max_results, MAX_RESULTS_CAP)
    results = docs_index.search(query, max_results)

    if not results:
        return f"No results found for query: {query}"

    response = f"# Search Results for: {query}\n\n"
    for i, result in enumerate(results, 1):
        response += f"## Result {i}: {result['section']}\n\n"
        response += f"{result['snippet']}\n\n"
        response += "---\n\n"
    return response


@server.tool(description="Get documentation for a specific Chainguard container image")
@safe_tool
def get_image_docs(
    image_name: Annotated[
        str, Field(description="Image name (e.g., 'python', 'node', 'nginx')")
    ],
) -> str:
    if docs_index is None:
        return DOCS_UNAVAILABLE

    image_name = image_name[:MAX_INPUT_LEN]
    docs = docs_index.get_image_docs(image_name)

    if docs:
        return f"# Documentation for {image_name}\n\n{docs}"
    return f"No documentation found for image: {image_name}"


@server.tool(
    description="List available Chainguard container images with optional filtering"
)
@safe_tool
def list_images(
    # Named `filter` to preserve the 1.x tool's argument name; shadows the builtin
    # only within this function.
    filter: Annotated[
        Optional[str],
        Field(description="Filter images by name (e.g., 'python', 'nginx', 'go')"),
    ] = None,
) -> str:
    filter_term = filter[:MAX_INPUT_LEN] if filter else None

    # Use catalog if available for richer results
    if catalog.available:
        results = catalog.list_images(filter_term)
        if not results:
            return f"No images found matching filter: {filter_term}"

        response = f"# Chainguard Container Images ({len(results)} results)\n\n"
        for img in results:
            line = f"- **{img['name']}** (`{img['registry_ref']}`)"
            if img.get("has_documentation"):
                line += " [docs]"
            response += line + "\n"
        return response
    else:
        # Fallback to docs-only listing
        images = docs_index.images if docs_index else []
        if filter_term:
            images = [i for i in images if filter_term.lower() in i.lower()]
        images_list = "\n".join([f"- {img}" for img in images])
        return f"# Available Chainguard Container Images\n\n{images_list}"


@server.tool(
    description="Get security-related documentation including CVE management and SBOMs"
)
@safe_tool
def get_security_docs() -> str:
    if docs_index is None:
        return DOCS_UNAVAILABLE
    return docs_index.get_security_content()


@server.tool(
    description="Get documentation for Chainguard tools (wolfi, apko, melange, chainctl)"
)
@safe_tool
def get_tool_docs(
    tool_name: Annotated[
        str, Field(description="Tool name: wolfi, apko, melange, or chainctl")
    ],
) -> str:
    if docs_index is None:
        return DOCS_UNAVAILABLE

    tool_name = tool_name[:MAX_INPUT_LEN]
    docs = docs_index.get_tool_docs(tool_name)

    if docs:
        return f"# {tool_name.title()} Documentation\n\n{docs}"
    return f"No documentation found for tool: {tool_name}"


@server.tool(
    description="Find Wolfi package equivalents for Debian, Fedora, or Alpine packages (e.g., Debian 'build-essential' -> Wolfi 'build-base')"
)
@safe_tool
def find_package_equivalent(
    package: Annotated[
        str,
        Field(
            description="OS package name (e.g., 'build-essential', 'libssl-dev', 'python3-pip')"
        ),
    ],
    distro: Annotated[
        Optional[Literal["debian", "fedora", "alpine"]],
        Field(
            description="Source distro to search: 'debian', 'fedora', or 'alpine'. Searches all if omitted."
        ),
    ] = None,
) -> str:
    package = package[:MAX_INPUT_LEN]
    if not catalog.available:
        return "Image catalog not available. Cannot look up package equivalents."

    results = catalog.find_package_equivalent(package, distro)
    if results:
        response = f"# Wolfi Equivalents for `{package}`\n\n"
        for r in results:
            wolfi_pkgs = (
                ", ".join(r["wolfi_packages"])
                if r["wolfi_packages"]
                else "(no direct equivalent)"
            )
            response += (
                f"- **{r['distro']}** `{r['original_package']}` -> `{wolfi_pkgs}`\n"
            )
        response += "\nInstall in a Wolfi-based image with:\n```\napk add "
        # Use first result's wolfi packages
        first_pkgs = results[0]["wolfi_packages"]
        response += " ".join(first_pkgs) if first_pkgs else "<package>"
        response += "\n```"
        return response
    else:
        search_note = f" in {distro}" if distro else ""
        return f"No Wolfi package equivalent found for `{package}`{search_note}. The package may use the same name in Wolfi, or check https://packages.wolfi.dev"


@server.tool(
    description="Check a Chainguard image's availability and tags via live registry query to cgr.dev (falls back to catalog data if no network)"
)
@safe_tool
def check_image_freshness(
    image_name: Annotated[
        str,
        Field(description="Chainguard image name (e.g., 'python', 'node', 'nginx')"),
    ],
) -> str:
    image_name = image_name[:MAX_INPUT_LEN]
    result = catalog.check_live_image(image_name)

    response = f"# Image Check: {image_name}\n\n"
    response += f"- **Registry ref**: `{result['registry_ref']}`\n"
    response += (
        f"- **Live check**: {'Success' if result['live_check'] else 'Not performed'}\n"
    )
    if result.get("error"):
        response += f"- **Note**: {result['error']}\n"
    if result.get("tags"):
        response += (
            f"- **Tags** ({len(result['tags'])}): {', '.join(result['tags'][:10])}\n"
        )
    if result.get("has_documentation") is not None:
        response += f"- **Has documentation**: {'Yes' if result['has_documentation'] else 'No'}\n"
    return response


def parse_args():
    """Parse command-line arguments with env var fallbacks."""
    parser = argparse.ArgumentParser(
        description="Chainguard AI Documentation MCP Server"
    )
    parser.add_argument(
        "--transport",
        choices=["stdio", "http"],
        default=os.getenv("MCP_TRANSPORT", "stdio"),
        help="Transport mode (default: stdio, env: MCP_TRANSPORT)",
    )
    parser.add_argument(
        "--host",
        # Binding all interfaces is required inside the Cloud Run container; the
        # service is fronted by Cloud Run, not exposed on the host directly.
        default=os.getenv("MCP_HOST", "0.0.0.0"),  # nosec B104
        help="HTTP server host (default: 0.0.0.0, env: MCP_HOST)",
    )
    parser.add_argument(
        "--port",
        type=int,
        default=int(os.getenv("MCP_PORT", "8080")),
        help="HTTP server port (default: 8080, env: MCP_PORT)",
    )
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()

    if args.transport == "http":
        # host must be passed explicitly: the SDK runner defaults to 127.0.0.1,
        # but Cloud Run requires binding 0.0.0.0. streamable_http_path defaults
        # to "/mcp" (matches the 1.x mount) and max_request_body_size to 4 MiB.
        server.run(transport="streamable-http", host=args.host, port=args.port)
    else:
        server.run()  # stdio
