#!/usr/bin/env python3
"""
Chainguard AI Documentation MCP Server

A Model Context Protocol server that provides AI assistants with searchable
access to Chainguard documentation including container images, security info,
and tooling guides.

Ported to the mcp 2.0 high-level `MCPServer` API (decision: DOCS-89). All tool
logic and both index classes are unchanged from the 1.x server; only the MCP
glue (registration + transport) was rewritten.
"""

import argparse
import functools
import json
import logging
import os
import re
from datetime import datetime, timezone
from typing import Any, Annotated, Dict, List, Literal, Optional

# MCP SDK imports (2.0 high-level API)
try:
    from mcp.server import MCPServer
    from pydantic import Field
except ImportError:
    import sys

    print(
        "Error: MCP SDK 2.x not installed. Install with: pip install 'mcp>=2,<3'",
        file=sys.stderr,
    )
    sys.exit(1)

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("chainguard-ai-docs-mcp")

# Documentation file path
DOCS_PATH = os.getenv("DOCS_PATH", "/docs/chainguard-ai-docs.md")

# Image catalog file path (generated by generate_image_catalog.py)
CATALOG_PATH = os.getenv("CATALOG_PATH", "/docs/image-catalog.json")

# Input length limits to prevent CPU DoS on string operations
MAX_INPUT_LEN = 500
MAX_RESULTS_CAP = 20

# Registry details for the anonymous cgr.dev pull path. The Docker Registry v2
# API requires a bearer token even for public images, so every live check is a
# token exchange followed by the real request. cgr.dev issues these tokens to
# unauthenticated callers, so this needs no credential (DOCS-173).
REGISTRY_DOMAIN = "cgr.dev"
REGISTRY_HOST = f"https://{REGISTRY_DOMAIN}"
REGISTRY_NAMESPACE = "chainguard"
REGISTRY_TIMEOUT = 10.0

# Accept both OCI and Docker manifest media types, index types first: Chainguard
# images are multi-arch, so `latest` resolves to an image index rather than to a
# single-platform manifest.
MANIFEST_ACCEPT = ", ".join(
    [
        "application/vnd.oci.image.index.v1+json",
        "application/vnd.docker.distribution.manifest.list.v2+json",
        "application/vnd.oci.image.manifest.v1+json",
        "application/vnd.docker.distribution.manifest.v2+json",
    ]
)

# A signed image carries three cosign attachment tags per digest
# (`sha256-<digest>.sig`, `.att` and `.sbom`), which outnumber real tags by
# roughly 500 to 1. They are filtered out of tag listings.
COSIGN_ATTACHMENT_PREFIX = "sha256-"

# compile_docs.py writes every documentation page as
#     ### <title>
#     _Path: <source path>_
#     <page content>
# so the title line plus the path line is a page boundary. Nothing else in the
# bundle carries that pair: page bodies keep their own '##' and '###' headings,
# which is why heading level alone cannot mark where a page starts (DOCS-181).
PAGE_HEADING = re.compile(
    r"^### (?P<title>.+)\n_Path: (?P<path>.+?)_\s*$", re.MULTILINE
)

# Everything from this marker on is container-image READMEs, delimited by
# IMAGE_SEPARATOR rather than by the page signature above.
IMAGES_MARKER = re.compile(r"^## Container Images\n", re.MULTILINE)

# Search scoring (DOCS-181). The previous scorer counted the whole query as one
# literal substring, so 'migrating python' scored zero everywhere — those two
# words are never adjacent in the corpus, even on the page titled "Migrating to
# Python Chainguard Containers". Score per term instead, and weight the title,
# because callers search for what a page is about rather than for a phrase it
# happens to contain.
SEARCH_TERM = re.compile(r"[a-z0-9][a-z0-9._/-]*")

# Words that appear in nearly every section, plus the ones an MCP client tends
# to wrap a question in ("give me the guide for ...").
SEARCH_STOPWORDS = frozenset(
    """a an and are as at be by can do does for from get give had has have how
    i in into is it me my of on or please show that the their them then there
    these this to use used using want was what when where which who why will
    with you your""".split()
)

# Suffixes stripped to a common stem so 'migration' and 'migrating' match. This
# is deliberately cruder than a real stemmer: the stem is then counted as a
# substring of the section text, so over-matching costs recall noise rather
# than a miss, and it needs no dependency and no pass over the 14 MB bundle.
STEM_SUFFIXES = (
    "ations",
    "ation",
    "ings",
    "ing",
    "ments",
    "ment",
    "ions",
    "ion",
    "es",
    "s",
)
MIN_STEM_LEN = 4

TITLE_TERM_WEIGHT = 40  # a term in the page title
TERM_COVERAGE_WEIGHT = 10  # each distinct query term the section matches
EXACT_PHRASE_BONUS = 60  # the whole query, verbatim
BODY_HIT_CAP = 20  # ceiling on raw frequency, so long pages cannot dominate

# Where the bundled pages are published, so a search result can link to the
# page rather than only naming it.
EDU_BASE_URL = "https://edu.chainguard.dev"


def page_url(source_path: str) -> str:
    """Map a bundle '_Path:' value to the published page URL.

    compile_docs.py records the path relative to content/, and Hugo serves
    'chainguard/libraries/python/overview.md' at
    '<base>/chainguard/libraries/python/overview/'.

    Both bundle forms are served at the directory rather than below it: a
    branch bundle (_index.md, 32 pages) and a leaf bundle (index.md, 76
    pages). Keeping the filename would 404 on 13% of the corpus. Verified
    against the live site (DOCS-181).
    """
    slug = source_path.removesuffix(".md")
    slug = slug.removesuffix("/_index").removesuffix("/index")
    if slug in ("_index", "index"):
        return f"{EDU_BASE_URL}/"
    return f"{EDU_BASE_URL}/{slug}/"


def extract_image_names(container_section: str) -> List[str]:
    """Return image names from the compiled '## Container Images' section text.

    compile_docs.py writes each image as
        ### <name>
        <README content>
        <!-- IMAGE_SEPARATOR -->
    so we split on the separator and take the first '### ' heading of each block.
    This is robust to '###' subheadings inside a README (which defeated the older
    regexes) and to image names containing underscores (e.g. sql_exporter).
    Uppercase scaffolding directories such as TEMPLATE are excluded by the
    lowercase-only name pattern.

    NOTE: keep this identical to extract_image_names in
    scripts/generate_image_catalog.py. The MCP server and the catalog must agree
    on the image set; see DOCS-138.
    """
    names = []
    for block in container_section.split("<!-- IMAGE_SEPARATOR -->"):
        heading = re.search(r"^### (\S+)\s*$", block, re.MULTILINE)
        if heading and re.fullmatch(r"[a-z0-9][a-z0-9_-]*", heading.group(1)):
            names.append(heading.group(1))
    return names


class ChaguardDocsIndex:
    """Index of Chainguard documentation sections for efficient retrieval."""

    def __init__(self, docs_content: str):
        self.content = docs_content
        self.sections, self.page_paths = self._parse_sections()
        self.images = self._extract_images()

    def _parse_sections(self) -> tuple[Dict[str, str], Dict[str, str]]:
        """Split the bundle into one section per documentation page or image.

        Returns the sections keyed by page title (or 'image:<name>'), and the
        source path of each page.

        The previous parser started a new section at any line beginning with
        '# '. compile_docs.py never emits that as structure, so every such line
        was content — a shell comment inside a fenced block, or an H1 in an
        image README. Page text ended up filed under keys like 'Install
        Composer and set up application', and whole guides became unfindable
        (DOCS-181). Key on what the compiler actually writes instead.
        """
        sections = {}
        page_paths = {}

        images_marker = IMAGES_MARKER.search(self.content)
        docs_region = (
            self.content[: images_marker.start()] if images_marker else self.content
        )

        headings = list(PAGE_HEADING.finditer(docs_region))

        # Whatever precedes the first page is the bundle's own front matter:
        # the usage guide that tells an AI client how to query this file.
        preamble = docs_region[: headings[0].start()] if headings else docs_region
        if preamble.strip():
            sections["Bundle Usage Guide"] = preamble.strip()

        for i, heading in enumerate(headings):
            end = headings[i + 1].start() if i + 1 < len(headings) else len(docs_region)
            title = heading.group("title").strip()
            path = heading.group("path").strip()

            # A handful of titles repeat across languages ('Global
            # configuration' exists for Java, JavaScript and Python). Qualify
            # the duplicates so one does not overwrite the others.
            key = title if title not in sections else f"{title} ({path})"

            sections[key] = docs_region[heading.start() : end].strip()
            page_paths[key] = path

        sections.update(self._parse_image_sections(images_marker))
        return sections, page_paths

    def _parse_image_sections(self, images_marker) -> Dict[str, str]:
        """Parse the container-image READMEs into 'image:<name>' sections.

        Pattern: ### image-name followed by content until <!-- IMAGE_SEPARATOR -->
        or end of string. Name class allows underscores to match images like
        sql_exporter (DOCS-138).

        Anything after the last separator is dropped. The bundle currently ends
        there; if the DFC mappings section returns (DOCS-174), index it here.
        """
        if not images_marker:
            return {}

        image_pattern = (
            r"### ([a-z0-9][a-z0-9_-]*)\n(.*?)(?=\n<!-- IMAGE_SEPARATOR -->|\Z)"
        )
        return {
            f"image:{match.group(1)}": f"### {match.group(1)}\n{match.group(2).strip()}"
            for match in re.finditer(
                image_pattern, self.content[images_marker.end() :], re.DOTALL
            )
        }

    def _extract_images(self) -> List[str]:
        """Extract list of container image names from docs."""
        container_images_match = IMAGES_MARKER.search(self.content)
        if container_images_match:
            names = extract_image_names(self.content[container_images_match.end() :])
            if names:
                return sorted(set(names))

        # Fallback: look for cgr.dev references if no images found from headers
        images = set()
        for match in re.finditer(r"cgr\.dev/chainguard/([a-z0-9\-]+)", self.content):
            images.add(match.group(1))
        return sorted(images)

    def search(self, query: str, max_results: int = 5) -> List[Dict[str, str]]:
        """Search documentation for relevant content."""
        stems = self._query_stems(query)
        if not stems:
            return []

        query_lower = query.lower().strip()
        results = []

        for section_name, section_content in self.sections.items():
            score = self._score_section(
                section_name, section_content, stems, query_lower
            )

            if score > 0:
                source_path = self.page_paths.get(section_name)
                results.append(
                    {
                        "section": section_name,
                        "score": score,
                        # Image READMEs are not published pages, so they have
                        # no path and no URL to offer.
                        "url": page_url(source_path) if source_path else "",
                        "snippet": self._build_snippet(section_content, stems),
                        "full_content": section_content[:2000],  # First 2000 chars
                    }
                )

        # Sort by relevance and return top results
        results.sort(key=lambda x: x["score"], reverse=True)
        return results[:max_results]

    @staticmethod
    def _stem(word: str) -> str:
        """Strip one common suffix, leaving at least MIN_STEM_LEN characters."""
        for suffix in STEM_SUFFIXES:
            if word.endswith(suffix) and len(word) - len(suffix) >= MIN_STEM_LEN:
                return word[: -len(suffix)]
        return word

    @classmethod
    def _query_stems(cls, query: str) -> List[str]:
        """Reduce a query to the distinct stems worth searching for.

        'Give me the migration guide for python' becomes ['migrat', 'guide',
        'python']. Returns them in query order, deduplicated.
        """
        stems = []
        for word in SEARCH_TERM.findall(query.lower()):
            if word in SEARCH_STOPWORDS:
                continue
            stem = cls._stem(word)
            if len(stem) >= MIN_STEM_LEN and stem not in stems:
                stems.append(stem)
        return stems

    @staticmethod
    def _score_section(
        section_name: str, section_content: str, stems: List[str], query_lower: str
    ) -> int:
        """Rank one section against the query stems.

        Reward breadth first — a section matching every term beats one matching
        a single term many times — then the title, then raw frequency.
        """
        title_lower = section_name.lower()
        content_lower = section_content.lower()

        matched = 0
        score = 0
        for stem in stems:
            hits = content_lower.count(stem)
            if hits:
                matched += 1
                score += min(hits, BODY_HIT_CAP)
            if stem in title_lower:
                score += TITLE_TERM_WEIGHT

        if not matched:
            return 0

        score += matched * TERM_COVERAGE_WEIGHT
        if query_lower in content_lower:
            score += EXACT_PHRASE_BONUS
        return score

    @staticmethod
    def _build_snippet(section_content: str, stems: List[str], limit: int = 5) -> str:
        """Return up to `limit` lines of the section worth showing the caller.

        Prefer lines mentioning the most query terms. The old version only
        looked at the first 50 lines of the section, so a match further down
        produced a result with an empty body — every hit in the DOCS-181 report
        read that way. Fall back to the opening prose so a result always says
        something.
        """
        lines = [line for line in section_content.split("\n") if line.strip()]

        scored = []
        for position, line in enumerate(lines):
            lowered = line.lower()
            hits = sum(1 for stem in stems if stem in lowered)
            if hits:
                scored.append((-hits, position, line))

        if scored:
            scored.sort()
            best = sorted(scored[:limit], key=lambda item: item[1])
            return "\n".join(line for _, _, line in best)

        opening = [line for line in lines if not line.startswith("_")]
        return "\n".join(opening[:limit])

    def get_image_docs(self, image_name: str) -> Optional[str]:
        """Get documentation for a specific container image."""
        # First, try to find the image-specific section (with image: prefix)
        image_key = f"image:{image_name}"
        if image_key in self.sections:
            return self.sections[image_key]

        # Fallback: try without exact match (case-insensitive)
        for section_name, section_content in self.sections.items():
            if (
                section_name.startswith("image:")
                and image_name.lower() in section_name.lower()
            ):
                return section_content

        # Last resort: search for any mention
        results = self.search(image_name, max_results=1)
        if results:
            return results[0]["full_content"]

        return None

    def get_security_content(self) -> str:
        """Get security and CVE related content."""
        security_terms = ["security", "cve", "vulnerability", "sbom", "signature"]
        relevant_sections = []

        for section_name, section_content in self.sections.items():
            if any(term in section_name.lower() for term in security_terms):
                relevant_sections.append(f"# {section_name}\n\n{section_content}")

        if relevant_sections:
            return "\n\n---\n\n".join(relevant_sections)

        return "No specific security documentation found."

    def get_tool_docs(self, tool_name: str) -> Optional[str]:
        """Get documentation for Chainguard tools (wolfi, apko, melange, chainctl)."""
        tool_lower = tool_name.lower()

        for section_name, section_content in self.sections.items():
            if tool_lower in section_name.lower():
                return section_content

        # Fallback to search
        results = self.search(tool_name, max_results=1)
        if results:
            return results[0]["full_content"]

        return None


class ImagesCatalog:
    """Catalog of Chainguard images and package mappings from image-catalog.json."""

    def __init__(self, catalog_path: str):
        self.catalog = self._load_catalog(catalog_path)

    def _load_catalog(self, path: str) -> Dict[str, Any]:
        """Load the catalog JSON, returning empty structure on failure."""
        try:
            with open(path, "r") as f:
                return json.load(f)
        except Exception as e:
            logger.warning(f"Could not load image catalog from {path}: {e}")
            return {
                "metadata": {},
                "images": {},
                "packages": {},
            }

    @property
    def available(self) -> bool:
        """Check if catalog data is loaded."""
        return bool(self.catalog.get("images"))

    def list_images(self, filter_term: Optional[str] = None) -> List[Dict[str, Any]]:
        """List images, optionally filtered by name."""
        results = []
        for name, entry in self.catalog.get("images", {}).items():
            if filter_term and filter_term.lower() not in name.lower():
                continue

            item = {
                "name": name,
                "registry_ref": entry.get("registry_ref", ""),
                "has_documentation": entry.get("has_documentation", False),
            }
            results.append(item)

        return sorted(results, key=lambda x: x["name"])

    def find_package_equivalent(
        self, package: str, distro: Optional[str] = None
    ) -> List[Dict[str, Any]]:
        """Find Wolfi package equivalents for a Debian, Fedora, or Alpine package."""
        results = []
        packages = self.catalog.get("packages", {})

        distros_to_search = [distro] if distro else list(packages.keys())

        for d in distros_to_search:
            pkg_map = packages.get(d, {})
            if package in pkg_map:
                results.append(
                    {
                        "distro": d,
                        "original_package": package,
                        "wolfi_packages": pkg_map[package],
                    }
                )
            else:
                # Case-insensitive search
                for key, value in pkg_map.items():
                    if key.lower() == package.lower():
                        results.append(
                            {
                                "distro": d,
                                "original_package": key,
                                "wolfi_packages": value,
                            }
                        )
                        break

        return results

    @staticmethod
    def _is_valid_image_name(name: str) -> bool:
        """Validate image name to prevent path traversal or injection.

        Underscores are allowed because real image names use them (sql_exporter,
        chrony_exporter); keep this name class in step with extract_image_names
        above, so an underscore name reports what the registry says rather than
        "Invalid image name" (DOCS-138, DOCS-173).
        """
        return bool(re.fullmatch(r"[a-z0-9][a-z0-9_-]{0,127}", name))

    @staticmethod
    def _fetch_pull_token(client: Any, repo: str) -> Dict[str, Any]:
        """Return an anonymous pull token for a repository.

        The token endpoint is where entitlement is enforced: it answers 403 for a
        repository the anonymous caller cannot pull, which is how an image that
        exists only in a private organization catalog presents itself here.
        """
        resp = client.get(
            f"{REGISTRY_HOST}/token",
            params={"scope": f"repository:{repo}:pull", "service": REGISTRY_DOMAIN},
        )
        if resp.status_code == 403:
            return {
                "token": None,
                "error": (
                    f"`{repo}` is not available for anonymous pull from the public "
                    f"{REGISTRY_DOMAIN} catalog. Images published only to a private "
                    "organization catalog are not visible to this server."
                ),
            }
        if resp.status_code != 200:
            return {
                "token": None,
                "error": (
                    f"Registry returned HTTP {resp.status_code} for the pull token"
                ),
            }
        return {"token": resp.json().get("token"), "error": None}

    @staticmethod
    def _age_in_days(built: str) -> Optional[int]:
        """Return whole days since an RFC 3339 build timestamp, or None."""
        try:
            # Normalize the "Z" suffix: fromisoformat rejects it before 3.11.
            stamp = datetime.fromisoformat(built.replace("Z", "+00:00"))
        except ValueError:
            return None
        return (datetime.now(timezone.utc) - stamp).days

    def _fetch_latest_metadata(
        self, client: Any, repo: str, headers: Dict[str, str]
    ) -> Dict[str, Any]:
        """Return the digest and build date of a repository's `latest` tag."""
        meta: Dict[str, Any] = {
            "digest": None,
            "built": None,
            "age_days": None,
            "error": None,
        }

        resp = client.get(
            f"{REGISTRY_HOST}/v2/{repo}/manifests/latest",
            headers={**headers, "Accept": MANIFEST_ACCEPT},
        )
        if resp.status_code == 404:
            meta["error"] = (
                f"No `latest` tag for {repo} in the public {REGISTRY_DOMAIN} catalog. "
                "Images published only to a private organization catalog are not "
                "visible to this server."
            )
            return meta
        if resp.status_code != 200:
            meta["error"] = (
                f"Registry returned HTTP {resp.status_code} for the manifest"
            )
            return meta

        meta["digest"] = resp.headers.get("Docker-Content-Digest")

        # Chainguard's build pipeline stamps the index with its build time. If an
        # image lacks the annotation, report the digest without a date rather
        # than inferring one.
        annotations = resp.json().get("annotations") or {}
        built = annotations.get("org.opencontainers.image.created")
        if built:
            meta["built"] = built
            meta["age_days"] = self._age_in_days(built)

        return meta

    @staticmethod
    def _fetch_real_tags(
        client: Any, repo: str, headers: Dict[str, str]
    ) -> Dict[str, Any]:
        """Return a repository's tags with cosign attachment tags removed."""
        listing: Dict[str, Any] = {"tags": [], "truncated": False, "error": None}

        resp = client.get(
            f"{REGISTRY_HOST}/v2/{repo}/tags/list",
            headers={**headers, "Accept": "application/json"},
        )
        if resp.status_code != 200:
            listing["error"] = (
                f"Registry returned HTTP {resp.status_code} for the tag list"
            )
            return listing

        listing["tags"] = [
            tag
            for tag in resp.json().get("tags") or []
            if not tag.startswith(COSIGN_ATTACHMENT_PREFIX)
        ]

        # The registry pages at 1000 tags and points to the next page with a Link
        # header. Rather than walking every page of attachment tags to find a
        # handful of real ones, flag the list as partial so a caller does not
        # read it as complete.
        listing["truncated"] = 'rel="next"' in resp.headers.get("Link", "")

        return listing

    def check_live_image(self, name: str) -> Dict[str, Any]:
        """Check image freshness via live registry query to cgr.dev.

        Reports the digest and build date of `latest` — the two facts that show
        whether an image is current — plus the repository's real tags.
        """
        result: Dict[str, Any] = {
            "name": name,
            "registry_ref": f"{REGISTRY_DOMAIN}/{REGISTRY_NAMESPACE}/{name}",
            "live_check": False,
            "tags": [],
            "tags_truncated": False,
            "digest": None,
            "built": None,
            "age_days": None,
            "error": None,
        }

        if not self._is_valid_image_name(name):
            result["error"] = "Invalid image name"
            return result

        # Add catalog info if available
        catalog_entry = self.catalog.get("images", {}).get(name)
        if catalog_entry:
            result["has_documentation"] = catalog_entry.get("has_documentation", False)

        try:
            import httpx
        except ImportError:
            result["error"] = "httpx not available; returning catalog data only"
            return result

        repo = f"{REGISTRY_NAMESPACE}/{name}"
        try:
            with httpx.Client(timeout=REGISTRY_TIMEOUT) as client:
                auth = self._fetch_pull_token(client, repo)
                if not auth["token"]:
                    result["error"] = (
                        auth["error"]
                        or f"Could not get an anonymous pull token from {REGISTRY_DOMAIN}"
                    )
                    return result

                headers = {"Authorization": f"Bearer {auth['token']}"}

                metadata = self._fetch_latest_metadata(client, repo, headers)
                if metadata["error"]:
                    result["error"] = metadata["error"]
                    return result

                result["digest"] = metadata["digest"]
                result["built"] = metadata["built"]
                result["age_days"] = metadata["age_days"]

                listing = self._fetch_real_tags(client, repo, headers)
                result["tags"] = listing["tags"]
                result["tags_truncated"] = listing["truncated"]
                result["error"] = listing["error"]

                # The manifest came back, so the live data above is good even if
                # the tag listing failed.
                result["live_check"] = True
        except Exception as e:
            result["error"] = f"Live check failed: {str(e)}"

        return result


# Initialize MCP server
server = MCPServer("chainguard-ai-docs")

# Load and index documentation
logger.info(f"Loading documentation from {DOCS_PATH}")
try:
    with open(DOCS_PATH, "r") as f:
        docs_content = f.read()
    docs_index = ChaguardDocsIndex(docs_content)
    logger.info(f"Indexed {len(docs_index.sections)} documentation sections")
    logger.info(f"Found {len(docs_index.images)} container images")
except Exception as e:
    logger.error(f"Failed to load documentation: {e}")
    docs_index = None

# Load image catalog
logger.info(f"Loading image catalog from {CATALOG_PATH}")
catalog = ImagesCatalog(CATALOG_PATH)
if catalog.available:
    logger.info(
        f"Catalog loaded: {catalog.catalog['metadata'].get('total_images', 0)} images"
    )
else:
    logger.warning(
        "Image catalog not available; catalog-based tools will return limited results"
    )


def safe_tool(fn):
    """Wrap a tool so uncaught exceptions are logged and never leak to the client.

    Preserves the 1.x server's behavior: on error, log with a stack trace and
    return a sanitized message instead of the raw exception text.
    """

    @functools.wraps(fn)
    def wrapper(*args, **kwargs):
        try:
            return fn(*args, **kwargs)
        except Exception:
            logger.error(f"Error handling tool call {fn.__name__}", exc_info=True)
            return "An internal error occurred. Please try again or adjust your query."

    return wrapper


DOCS_UNAVAILABLE = "Error: Documentation not loaded. Please check server logs."


@server.tool(
    description="Search across all Chainguard documentation for relevant content"
)
@safe_tool
def search_docs(
    query: Annotated[
        str,
        Field(
            description="Search query (e.g., 'python image security', 'CVE management')"
        ),
    ],
    max_results: Annotated[
        int,
        Field(
            description="Maximum number of results to return (default: 5)",
            le=MAX_RESULTS_CAP,
        ),
    ] = 5,
) -> str:
    if docs_index is None:
        return DOCS_UNAVAILABLE

    query = query[:MAX_INPUT_LEN]
    max_results = min(max_results, MAX_RESULTS_CAP)
    results = docs_index.search(query, max_results)

    if not results:
        return f"No results found for query: {query}"

    response = f"# Search Results for: {query}\n\n"
    for i, result in enumerate(results, 1):
        response += f"## Result {i}: {result['section']}\n\n"
        if result["url"]:
            response += f"{result['url']}\n\n"
        response += f"{result['snippet']}\n\n"
        response += "---\n\n"
    return response


@server.tool(description="Get documentation for a specific Chainguard container image")
@safe_tool
def get_image_docs(
    image_name: Annotated[
        str, Field(description="Image name (e.g., 'python', 'node', 'nginx')")
    ],
) -> str:
    if docs_index is None:
        return DOCS_UNAVAILABLE

    image_name = image_name[:MAX_INPUT_LEN]
    docs = docs_index.get_image_docs(image_name)

    if docs:
        return f"# Documentation for {image_name}\n\n{docs}"
    return f"No documentation found for image: {image_name}"


@server.tool(
    description="List available Chainguard container images with optional filtering"
)
@safe_tool
def list_images(
    # Named `filter` to preserve the 1.x tool's argument name; shadows the builtin
    # only within this function.
    filter: Annotated[
        Optional[str],
        Field(description="Filter images by name (e.g., 'python', 'nginx', 'go')"),
    ] = None,
) -> str:
    filter_term = filter[:MAX_INPUT_LEN] if filter else None

    # Use catalog if available for richer results
    if catalog.available:
        results = catalog.list_images(filter_term)
        if not results:
            return f"No images found matching filter: {filter_term}"

        response = f"# Chainguard Container Images ({len(results)} results)\n\n"
        for img in results:
            line = f"- **{img['name']}** (`{img['registry_ref']}`)"
            if img.get("has_documentation"):
                line += " [docs]"
            response += line + "\n"
        return response
    else:
        # Fallback to docs-only listing
        images = docs_index.images if docs_index else []
        if filter_term:
            images = [i for i in images if filter_term.lower() in i.lower()]
        images_list = "\n".join([f"- {img}" for img in images])
        return f"# Available Chainguard Container Images\n\n{images_list}"


@server.tool(
    description="Get security-related documentation including CVE management and SBOMs"
)
@safe_tool
def get_security_docs() -> str:
    if docs_index is None:
        return DOCS_UNAVAILABLE
    return docs_index.get_security_content()


@server.tool(
    description="Get documentation for Chainguard tools (wolfi, apko, melange, chainctl)"
)
@safe_tool
def get_tool_docs(
    tool_name: Annotated[
        str, Field(description="Tool name: wolfi, apko, melange, or chainctl")
    ],
) -> str:
    if docs_index is None:
        return DOCS_UNAVAILABLE

    tool_name = tool_name[:MAX_INPUT_LEN]
    docs = docs_index.get_tool_docs(tool_name)

    if docs:
        return f"# {tool_name.title()} Documentation\n\n{docs}"
    return f"No documentation found for tool: {tool_name}"


@server.tool(
    description="Find Wolfi package equivalents for Debian, Fedora, or Alpine packages (e.g., Debian 'build-essential' -> Wolfi 'build-base')"
)
@safe_tool
def find_package_equivalent(
    package: Annotated[
        str,
        Field(
            description="OS package name (e.g., 'build-essential', 'libssl-dev', 'python3-pip')"
        ),
    ],
    distro: Annotated[
        Optional[Literal["debian", "fedora", "alpine"]],
        Field(
            description="Source distro to search: 'debian', 'fedora', or 'alpine'. Searches all if omitted."
        ),
    ] = None,
) -> str:
    package = package[:MAX_INPUT_LEN]
    if not catalog.available:
        return "Image catalog not available. Cannot look up package equivalents."

    results = catalog.find_package_equivalent(package, distro)
    if results:
        response = f"# Wolfi Equivalents for `{package}`\n\n"
        for r in results:
            wolfi_pkgs = (
                ", ".join(r["wolfi_packages"])
                if r["wolfi_packages"]
                else "(no direct equivalent)"
            )
            response += (
                f"- **{r['distro']}** `{r['original_package']}` -> `{wolfi_pkgs}`\n"
            )
        response += "\nInstall in a Wolfi-based image with:\n```\napk add "
        # Use first result's wolfi packages
        first_pkgs = results[0]["wolfi_packages"]
        response += " ".join(first_pkgs) if first_pkgs else "<package>"
        response += "\n```"
        return response
    else:
        search_note = f" in {distro}" if distro else ""
        return f"No Wolfi package equivalent found for `{package}`{search_note}. The package may use the same name in Wolfi, or check https://packages.wolfi.dev"


@server.tool(
    description="Check how current a Chainguard image is via live registry query to cgr.dev: reports the digest and build date of `latest` plus the repository's tags (falls back to catalog data if no network)"
)
@safe_tool
def check_image_freshness(
    image_name: Annotated[
        str,
        Field(description="Chainguard image name (e.g., 'python', 'node', 'nginx')"),
    ],
) -> str:
    image_name = image_name[:MAX_INPUT_LEN]
    result = catalog.check_live_image(image_name)

    response = f"# Image Check: {image_name}\n\n"
    response += f"- **Registry ref**: `{result['registry_ref']}`\n"
    response += (
        f"- **Live check**: {'Success' if result['live_check'] else 'Not performed'}\n"
    )
    if result.get("digest"):
        response += f"- **Current digest** of `latest`: `{result['digest']}`\n"
    if result.get("built"):
        age = result.get("age_days")
        age_note = ""
        if age == 0:
            age_note = " (today)"
        elif age is not None:
            age_note = f" ({age} day{'' if age == 1 else 's'} ago)"
        response += f"- **Built**: {result['built']}{age_note}\n"
    if result.get("error"):
        response += f"- **Note**: {result['error']}\n"
    if result.get("tags"):
        response += (
            f"- **Tags** ({len(result['tags'])}): {', '.join(result['tags'][:10])}\n"
        )
        if result.get("tags_truncated"):
            response += (
                "- **Tag list**: partial. The registry paged the response, so more "
                "tags may exist beyond those listed.\n"
            )
    if result.get("has_documentation") is not None:
        response += f"- **Has documentation**: {'Yes' if result['has_documentation'] else 'No'}\n"
    return response


def parse_args():
    """Parse command-line arguments with env var fallbacks."""
    parser = argparse.ArgumentParser(
        description="Chainguard AI Documentation MCP Server"
    )
    parser.add_argument(
        "--transport",
        choices=["stdio", "http"],
        default=os.getenv("MCP_TRANSPORT", "stdio"),
        help="Transport mode (default: stdio, env: MCP_TRANSPORT)",
    )
    parser.add_argument(
        "--host",
        # Binding all interfaces is required inside the Cloud Run container; the
        # service is fronted by Cloud Run, not exposed on the host directly.
        default=os.getenv("MCP_HOST", "0.0.0.0"),  # nosec B104
        help="HTTP server host (default: 0.0.0.0, env: MCP_HOST)",
    )
    parser.add_argument(
        "--port",
        type=int,
        default=int(os.getenv("MCP_PORT", "8080")),
        help="HTTP server port (default: 8080, env: MCP_PORT)",
    )
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()

    if args.transport == "http":
        # host must be passed explicitly: the SDK runner defaults to 127.0.0.1,
        # but Cloud Run requires binding 0.0.0.0. streamable_http_path defaults
        # to "/mcp" (matches the 1.x mount) and max_request_body_size to 4 MiB.
        server.run(transport="streamable-http", host=args.host, port=args.port)
    else:
        server.run()  # stdio
