issuer: https://token.actions.githubusercontent.com
subject: repo:chainguard-dev/edu:.*
claim_pattern:
  job_workflow_ref: chainguard-dev/edu/.github/workflows/autodocs-platform.yaml@.*

permissions:
  contents: write # writes to the repo
  pull_requests: write # to create pull requests
