package:
  name: academy-apko
  version: 0.1.0
  description: Chainguard Academy apko image
  target-architecture:
    - aarch64
    - x86_64
  copyright:
    - license: Apache-2.0
      paths:
        - "*"

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    packages:
      - alpine-baselayout-data
      - ca-certificates-bundle
      - busybox

pipeline:
  - name: Setup stuff
    runs: |
      mkdir -p \
        "${{targets.destdir}}/usr/bin" \
        "${{targets.destdir}}/usr/local/bin" \
        "${{targets.destdir}}/etc/profile.d" \
        "${{targets.destdir}}/etc/sudoers.d"
      echo "inky ALL=(ALL:ALL) NOPASSWD: ALL" > "${{targets.destdir}}/etc/sudoers.d/wheel"
      cp ./profile.sh "${{targets.destdir}}/etc/profile.d/inky-profile.sh"
